backend/modules/metadata_store/local.py
backend/modules/vector_db/qdrant.py
backend/modules/vector_db/weaviate.py
backend/requirements.txt
backend/settings.py
backend/types.py

Reverts truefoundry/docs-qa-playground#82

Revert "Updated weaviate client, fixed bugs, added functions to create collection in weaviate"

---

frontend/src/components/base/atoms/Badge.tsx
frontend/src/screens/dashboard/docsqa/settings/DataSourcesTable.tsx

https://truefoundry.atlassian.net/browse/TT-6380

UI: add run status badge

---

backend/modules/rerankers/mxbai_reranker.py

Explicitly pick cuda or cpu in reranker

---

README.md
compose.env
docker-compose.yaml

Great work, here are some suggestions. 
Closes #214 
Please review, I just "eye-balled' the edits in Github UI without broad testing. Pretty confident that it works, except for typos.

Infinity suggestions for deployment

---

backend/modules/vector_db/qdrant.py
backend/types.py
compose.env

Refactor qdrant client config parsing

---

backend/modules/model_gateway/__init__.py
backend/modules/model_gateway/model_gateway.py
backend/modules/query_controllers/example/types.py
backend/modules/query_controllers/multimodal/types.py
backend/server/routers/internal.py
backend/types.py
compose.env
docker-compose.yaml

Ignore registering models if API key is not present, and put out a war…ning. Also create a config.json file at runtime, helpful for template deployments

Fix models_config.json file issue

---

docker-compose.yaml

Update docker-compose.yaml - infinity

---

backend/database/schema.prisma
backend/modules/metadata_store/base.py
backend/modules/metadata_store/prismastore.py
backend/modules/metadata_store/truefoundry.py
backend/server/app.py
backend/server/routers/rag_apps.py
backend/types.py
frontend/package.json
frontend/src/router/DocsQA.tsx
frontend/src/screens/dashboard/docsqa/Applications/index.tsx
frontend/src/screens/dashboard/docsqa/Chatbot/index.tsx
frontend/src/screens/dashboard/docsqa/Navbar.tsx
frontend/src/screens/dashboard/docsqa/index.tsx
frontend/src/stores/qafoundry/index.ts
frontend/yarn.lock

TODO: support for prisma store - ✅

Save RAG Apps from query controller payload

---

.gitignore
backend/modules/metadata_store/prismastore.py
backend/modules/query_controllers/example/controller.py
backend/modules/query_controllers/multimodal/controller.py
backend/requirements.txt
backend/server/routers/internal.py
backend/settings.py
backend/types.py
compose.env
docker-compose.yaml
models_config.truefoundry.yaml

- Remove artificial sleeps
- Add gpt-4o-mini and small embeddings + misc
- upgrade truefoundry[ml], pydantic
- Remove hardcoded /app/user_data

Remove artificial sleeps, add gpt-4o-mini and small embeddings + misc

---

backend/server/app.py

- Refactored `AsyncProcessPoolExecutor` to correctly handle coroutines and awaitables
- Implemented an asynchronous `submit` method in `AsyncProcessPoolExecutor`
- Added a periodic health check mechanism in the process pool lifespan manager
- Introduced an automatic restart feature for the process pool on detected failures
- Enhanced exception handling and logging for tasks submitted to the process pool
These changes address stability issues we've been experiencing with process pool, particularly when tasks raise unhandled exceptions. The new implementation provides better visibility into errors occurring within pool tasks and implements a self-healing mechanism to maintain system stability.
1. **Proper Coroutine Handling**: The `AsyncProcessPoolExecutor` now correctly manages coroutines, …

# Improved Process Pool Management and Error Handling

---

deployment/indexer.py

- **chore: implement carbon**
- **fix import**
- **fix: escaped command**

Fix Index command for the indexer

---

backend/modules/dataloaders/truefoundryloader.py
backend/server/routers/internal.py
backend/utils.py

- Remove support for `artifacts` in TruefoundryLoader
- Extract `tfy_client` to utils to avoid creating multiple tfy clients
- refactor tfy loader with exception handling

feat: remove tfy loader

---

frontend/src/screens/dashboard/docsqa/Chatbot/index.tsx
frontend/tailwind.config.ts

Updated the UI for the QA Chatbot component.
Modified the Tailwind CSS configuration to add new animations.
@Blakeinstein  and @sayan-truefoundry  
Please review the modifications and let me know if any changes are needed.
Thank You.

Updated UI for Cognita-Truefoundry Docs QA Bot

---

frontend/src/screens/dashboard/docsqa/NewCollection.tsx

Update  the NewCollection component by making the error messages clearer.
@Blakeinstein  
Please review the changes  and comment if any change is required.

UI-Fix for collection creation error

---

.pre-commit-config.yaml
backend/indexer/indexer.py
backend/modules/dataloaders/loader.py
backend/modules/metadata_store/prisma_store.py
backend/modules/parsers/multi_modal_parser.py
backend/modules/parsers/parser.py
backend/modules/parsers/video_parser.py
backend/requirements.txt
backend/server/routers/data_source.py
backend/server/routers/internal.py
backend/types.py
deployment/indexer.py
deployment/unstructured_io.py

- Add `autoflake` to remove unused imports in the pre-commit config
- Add comments and grouped together similar libraries in requirements.txt
- removed unused libraries: `gunicorn`, `python-multipart`, `tiktoken`

feat: add autoflake to pre commit config

---

backend/modules/model_gateway/audio_processing_svc.py
backend/modules/model_gateway/model_gateway.py
backend/modules/model_gateway/reranker_svc.py
backend/requirements.txt

Reverts truefoundry/cognita#366

Revert "feat: add caching to model gateway, add code documentation"

---

frontend/src/index.scss
frontend/src/screens/dashboard/docsqa/Applications/index.tsx
frontend/src/screens/dashboard/docsqa/index.tsx

Added Curl request syntax for chatbot in config modal.

feat: Added curl command syntax in config for  chat-application 

---

deployment/audio.py
deployment/backend.py
deployment/deploy.py
deployment/frontend.py
deployment/indexer.py
deployment/infinity.py
deployment/postgres_database.py
deployment/qdrant.py
deployment/qdrant_ui.py
deployment/unstructured_io.py
frontend/Dockerfile

- **fix: use app set name as prefix**
- **fix: use kebab case for secret names**

Add application set name to services and use new secrets format

---

backend/modules/query_controllers/base.py
backend/server/routers/internal.py
backend/settings.py
backend/utils.py

- Add function to generate a signed URL by datapoint fqn of a chunk/document
- add model validation in settings to raise an error if local = true and ml repo is not provided

feat: parse data point fqn to fetch signed url

---

backend/modules/query_controllers/base.py

Since we want to fetch the signed URL when a user clicks on the source links in context, we don't want to pre-fetch the URLs while responding to the QnA API

feat: remove signed url generation on the fly during qna api response

---

frontend/src/screens/dashboard/docsqa/AddDataSourceToCollection.tsx
frontend/src/screens/dashboard/docsqa/Applications/index.tsx
frontend/src/screens/dashboard/docsqa/Chatbot/index.tsx
frontend/src/screens/dashboard/docsqa/DataSources/index.tsx
frontend/src/screens/dashboard/docsqa/NewCollection.tsx
frontend/src/screens/dashboard/docsqa/index.tsx
frontend/src/utils/error.ts

Fixed Error fixing by building custom error handler.
@Blakeinstein  and @sayan-truefoundry Can you review the updates.

Updated Error Handling

---

backend/requirements.txt

closes https://github.com/truefoundry/cognita/pull/400 and https://github.com/truefoundry/cognita/pull/397
Addresses security issue: https://github.com/truefoundry/cognita/security/dependabot/76

feat: upgrade langchain libraries

---

README.md

Update instructions on adding custom embedding models

---

backend/modules/model_gateway/model_gateway.py

Fix typo issue
The rerank model rerank-english-v2.0 is proved by cohere not OpenAI.

chore: fix Fix typo issue
